AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates a custom resource to verify a domain and its DKIM with SES
###Resources###
Resources:
  SESVerifyDomainCR:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        EnvironmentParameter: !Ref EnvironmentParameter
      TemplateURL: "./packages/cloudformation-ses-verifydomain/cf-packaged.yml"
  ACMValidationDNSCR:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        EnvironmentParameter: !Ref EnvironmentParameter
      TemplateURL: "./packages/cloudformation-acm-validationdns/cf-packaged.yml"
###Parameters###
Parameters:
  EnvironmentParameter:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Specifies whether dev, test, or prod environment. dev is default.