AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates a custom resource to verify a domain and its DKIM with SES
###Resources###
Resources:
  CloudformationSESVerifyDomainPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: Enables the CloudformationSESVerifyDomain custom resource to verify domains and DKIM and publish needed records
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - ses:VerifyDomainDkim
              - ses:VerifyDomainIdentity
            Resource:
              - "*"
          -
            Effect: "Allow"
            Action:
              - route53:GetHostedZone
              - route53:ChangeResourceRecordSets
              - route53:ListHostedZonesByName
            Resource:
              - "*"
      ManagedPolicyName: !Join [ "-", [cloudformation-ses-verifydomain-cr-access, !Ref EnvironmentParameter, !Ref "AWS::Region"]]
  CloudformationSESVerifyDomainRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      RoleName: !Join [ "-", [cloudformation-ses-verifydomain-cr-role, !Ref EnvironmentParameter, !Ref "AWS::Region"]]
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
      - !Ref CloudformationSESVerifyDomainPolicy
  CloudformationSESVerifyDomainFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Join [ "-", [cloudformation-ses-verifydomain-cr, !Ref EnvironmentParameter]]
      Handler: index.handler
      Runtime: nodejs8.10
      Code: .
      Description: Verifies a domain and DKIM for SES
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt CloudformationSESVerifyDomainRole.Arn
      TracingConfig:
        Mode: Active
  #Reference custom resource reference
  #CloudformationSESVerifyDomain:
  #  Type: Custom::CloudformationSESVerifyDomain
  #  Condition: CreateCustomResource
  #  Properties:
  #    ServiceToken: !GetAtt CloudformationSESVerifyDomain.Arn
  #    HostedZoneId: !Ref HostedZoneIdParameter
###Parameters###
Parameters:
  EnvironmentParameter:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Specifies whether dev, test, or prod environment. dev is default.
###Outputs###
Outputs:
  CloudformationSESVerifyDomainServiceToken:
    Description: Returns the service token for the CloudformationSESVerifyDomain custom resource
    Value: !GetAtt CloudformationSESVerifyDomainFunction.Arn
    Export:
      Name: CloudformationSESVerifyDomainServiceToken